### ISSUE TITLE
Model and model inputs needing to be on the same device

### ISSUE THREAD

**Issue by b4yuan** [bilalhsp/Auditory_Cortex#8]
https://github.com/bilalhsp/Auditory_Cortex/blob/d1b51847640b6793d5330b6c7691041d1d5b5558/auditory_cortex/feature_extractors.py#L158-L161

The above code was changed to address the `[RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same](https://stackoverflow.com/questions/59013109/runtimeerror-input-type-torch-floattensor-and-weight-type-torch-cuda-floatte)` error. Another fix could be `input = input.cuda()` after line 159. 

https://github.com/bilalhsp/Auditory_Cortex/blob/d1b51847640b6793d5330b6c7691041d1d5b5558/auditory_cortex/feature_extractors.py#L177

This line needed to be changed to `out = self.model(aud.cuda())` to address a `[RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! when resuming training](https://stackoverflow.com/questions/66091226/runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least)` error.

**Comment by bilalhsp** [comment]
This should be resolved now, at least for wave2letter_modified. I am not getting this error, so I am not able to verify it.
